[default_config]
assembler = "nasm"
instruction_set = "x86/x86-64"

[default_config.opts]
# compiler = "/Users/me/dev/asm/fasm/source/macos/x64/fasmg"
compiler = "fasmg"
command = "fasmg"
# compile_flags_txt = [
#     "your",
#     "arguments",
#     "to",
#     "nasm",
#     "here",
# ]
diagnostics = true
# default_diagnostcs = false

# [opts]
# # Enable diagnostics 
# diagnostics = true
# default_diagnostics = true
# compiler = "/Users/me/dev/asm/fasm/source/macos/x64/fasmg"
# # Set your compiler path
